DB bootstrap
Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>

Only install mockery when needed

Better definition of mocks (supports multi-threaded builds)

Add (optional) database to be used in unit testing

Run all workflows when Makefile.common changes

Fix runtime Makefile

clean up mock

Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>

remove test-full and tryout github action for db setup script

Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>

propose DB setup in github action and docker

Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>

turn off db for now

Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>

fixing linting

Signed-off-by: Chengxuan Xing <chengxuan.xing@kaleido.io>

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -1,70 +1,88 @@
 # You can override these variables in your Makefile
 SRC_DIR ?= ./pkg/...
+CREATE_TEST_DB ?= 1
 
-# The common tasks below
+# Common configuration
 VGO=go
 GOBIN := $(shell $(VGO) env GOPATH)/bin
 CGO_ENABLED=0
 GOGC=30
 MOCKERY := $(GOBIN)/mockery
+MOCKERY_VERSION := v2.40.2
+DOCKER=docker
+ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
 
-# Dependency
+# Install mockery if it is missing or at the wrong version
+GET_MOCKERY_VERSION = $(shell $(MOCKERY) --version)
+
+$(MOCKERY):
+	$(VGO) install github.com/vektra/mockery/v2@$(MOCKERY_VERSION)
+
+.PHONY: mockery
+mockery: $(MOCKERY)
+	@if [ $(GET_MOCKERY_VERSION) != "$(MOCKERY_VERSION)" ]; then \
+		echo "Replacing mockery (wrong version found)" ; \
+		$(MAKE) -B mockery; \
+	fi
+
+# General dependencies
 .PHONY: deps
-deps:
-		$(VGO) get $(SRC_DIR)
-		$(VGO) install github.com/vektra/mockery/v2@v2.40.2
-		$(VGO) mod tidy
+deps: mockery
+	$(VGO) get $(SRC_DIR)
+	$(VGO) mod tidy
 
-# None mock setup
-
-ifeq ($(MOCK_TARGET_DEFINED),)
-.PHONY: mock
-mock: deps
-		@echo "No mock required"
-#		${MOCKERY} --case underscore --dir ${BTXM_PATH} --name BlockchainTransactionManager --outpkg btxmMocks --output mocks/btxmMocks
-endif
-
-# # Example setup to override the default mock in common task below, must be declared before including the common Makefile
-# MOCK_TARGET_DEFINED := 1
-# .PHONY: btxmanager
-# btxmanager:
-# 		$(eval BTXM_PATH := $(shell $(VGO) list -f '{{.Dir}}' github.com/kaleido-io/paladin-blockchain-transaction-manager/pkg/manager))	
-
-# .PHONY: mock
-# mock: deps btxmanager
-# 		${MOCKERY} --case underscore --dir ${BTXM_PATH} --name BlockchainTransactionManager --outpkg btxmMocks --output mocks/btxmMocks
+# Mock setup
+# makemock arguments: (path to interface code) (interface name) (output package) (pre-req targets)
+.PHONY: mocks
+define makemock
+.PHONY: mocks-$(strip $(1))-$(strip $(2))
+mocks: mocks-$(strip $(1))-$(strip $(2))
+mocks-$(strip $(1))-$(strip $(2)): mockery $(4)
+	$(MOCKERY) --case underscore --dir $(1) --name $(2) --outpkg $(3) --output mocks/$(strip $(3))
+endef
 
 # Linting
-
 LINT := $(GOBIN)/golangci-lint
 .PHONY: lint
 lint: ${LINT}
-		GOGC=20 $(LINT) run -v --timeout 5m
-${LINT}:
-		$(VGO) install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
+	GOGC=20 $(LINT) run -v --timeout 5m
+$(LINT):
+	$(VGO) install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
+
+# Database container (if needed for testing)
+DB_COMPOSE_FILE := $(ROOT_DIR)/docker-compose-test.yml
+.PHONY: start-db stop-db
+start-db:
+	$(DOCKER) compose -f $(DB_COMPOSE_FILE) up -d
+stop-db:
+	$(DOCKER) compose -f $(DB_COMPOSE_FILE) down
 
 # Testing
+.PHONY: test-run coverage
+coverage: test-run
+	$(VGO) tool cover -html=coverage.txt
 
-.PHONY: test-no-coverage-check
-test-no-coverage-check: deps lint mock
-		$(VGO) test $(SRC_DIR)  -cover -coverprofile=coverage.txt -covermode=atomic -timeout=30s ${TEST_FLAGS};
-
-.PHONY: coverage
-coverage: test-no-coverage-check 
-		$(VGO) tool cover -html=coverage.txt
+test-run: deps lint mocks
+ifeq ($(CREATE_TEST_DB),1)
+	$(MAKE) start-db
+	$(VGO) test $(SRC_DIR) -cover -coverprofile=coverage.txt -covermode=atomic -timeout=30s $(TEST_FLAGS)
+	$(MAKE) stop-db
+else
+	$(VGO) test $(SRC_DIR) -cover -coverprofile=coverage.txt -covermode=atomic -timeout=30s $(TEST_FLAGS)
+endif
 
 # Target to enforce 100% coverage
 .PHONY: test
-test: test-no-coverage-check
-		@echo "Checking test coverage..."
-		@total_coverage=`$(VGO) tool cover -func=coverage.txt | grep total | awk '{print $$3}'`; \
-		if [ "$$total_coverage" != "100.0%" ]; then \
-			echo "ERROR: Coverage is not 100% (current coverage: $$total_coverage)"; \
-			exit 1; \
-		else \
-			echo "Coverage is 100%"; \
-		fi
-		@rm -f coverage.txt
+test: test-run
+	@echo "Checking test coverage..."
+	@total_coverage=`$(VGO) tool cover -func=coverage.txt | grep total | awk '{print $$3}'`; \
+	if [ "$$total_coverage" != "100.0%" ]; then \
+		echo "ERROR: Coverage is not 100% (current coverage: $$total_coverage)"; \
+		exit 1; \
+	else \
+		echo "Coverage is 100%"; \
+	fi
+	@rm -f coverage.txt
 
 # Docker build
 .PHONY: docker
